- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: install common package
  apt:
    force_apt_get: yes
    name:
      - vim
      - git
      - zip
      - unzip
      - lsof
      - python3
      - python
      - python-minimal